config/routes.rb
Rails.application.routes.draw do
  resources :admins
  root "home#index"
  #get 'home/index', to: "home#index"
  resources :applications
  resources :properties
  resources :applicants
  resources :agents
  resources :admins
  resources :session, only: [:new, :create, :destroy]
  get 'signup', to: "agents#new", as: 'signup'
  get 'app_signup', to: "applicants#new", as: 'app_signup'
  get 'login', to: "session#new", as: 'login'
  get 'logout', to: "session#destroy", as: 'logout'
  get 'admin_signup', to: "admins#new", as: 'admin_signup'
  get 'curr_applications', to: "applications#curr_applications", as: 'curr_applications'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field"  style="display: none" >
    <%= form.label :password %>
    <%= form.text_field :password, :readonly =>true %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email , :readonly =>true%>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.phone_number %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
<!--        <td><%#= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>ID:</strong>
  <%= @admin.id %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password_digest %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @admin.phone_number %>
</p>



<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>