config/routes.rb
Rails.application.routes.draw do
  resources :admins
  root "home#index"
  #get 'home/index', to: "home#index"
  resources :applications
  resources :properties
  resources :applicants
  resources :agents
  resources :admins
  resources :session, only: [:new, :create, :destroy]
  get 'signup', to: "agents#new", as: 'signup'
  get 'app_signup', to: "applicants#new", as: 'app_signup'
  get 'login', to: "session#new", as: 'login'
  get 'logout', to: "session#destroy", as: 'logout'
  get 'admin_signup', to: "admins#new", as: 'admin_signup'
  get 'curr_applications', to: "applications#curr_applications", as: 'curr_applications'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :applicant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_agent, :current_applicant, :current_admin
  helper_method :agent_logged_in?, :applicant_logged_in?, :admin_logged_in?
  #before_action :authorized

  def current_agent
    if session[:id] and session[:type] == "agent"
      @current_agent ||= Agent.find(session[:id])
    else
      @current_agent = nil
    end
  end

  def current_applicant
    if session[:id] and session[:type] == "applicant"
      @current_applicant ||= Applicant.find(session[:id])
    else
      @current_applicant = nil
    end
  end

  def current_admin
    if session[:id] and session[:type] == "admin"
      @current_admin ||= Admin.find(session[:id])
    else
      @current_admin = nil
    end
  end

  def agent_logged_in?
    !current_agent.nil?
  end

  def applicant_logged_in?
    !current_applicant.nil?
  end

  def admin_logged_in?
    !current_admin.nil?
  end

  def authorized
    redirect_to root_path unless agent_logged_in? or applicant_logged_in? or admin_logged_in?
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: %i[ show edit update destroy ]

  # GET /applications or /applications.json
  def index
    if(agent_logged_in?)
      @applications = Application.all
    else
      @applications = Application.where(applicant_id: session[:id])
     
    end
  end

  # GET /applications or /applications.json
  def curr_applications
    @applications = Application.where(applicant_id: session[:id])
  end

  # GET /applications/1 or /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new

  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications or /applications.json
  def create
    @application = Application.new(application_params)
    if(current_applicant)
       @application.applicant_id = current_applicant.id
    elsif(current_admin)
       @application.applicant_id = current_admin.id
    end

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: "Application was successfully created." }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1 or /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: "Application was successfully updated." }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1 or /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: "Application was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def application_params
      params.require(:application).permit(:applicant_id, :datetime, :property, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_with(model: application, local: true) do |form| %>
  <% if application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--  <div class="field">-->
    <%#= form.label :applicant %>
    <%#= form.number_field :applicant %>
<!--  </div>-->

  <div class="field">
    <%= form.label :datetime %>
    <%= form.date_select :datetime %>
  </div>

  <div class="field">
    <%= form.label :property %>
    <%= form.number_field :property %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/applications/curr_applications.html.erb
<p id="notice"><%= notice %></p>

<h1>Applications</h1>

<table>
  <thead>
  <tr>
    <th>Applicant</th>
    <th>Datetime</th>
    <th>Property</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @applications.each do |application| %>
    <tr>
      <td><%= application.applicant_id %></td>
      <td><%= application.datetime %></td>
      <td><%= application.property %></td>
      <td><%= application.status %></td>
      <td><%= link_to 'Show', application %></td>
      <td><%= link_to 'Edit', edit_application_path(application) %></td>
      <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applications</h1>

<table>
  <thead>
    <tr>
      <th>Applicant</th>
      <th>Datetime</th>
      <th>Property</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.applicant_id %></td>
        <td><%= application.datetime %></td>
        <td><%= application.property %></td>
        <td><%= application.status %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>ID:</strong>
  <%= @application.id %>
</p>


<p>
  <strong>Applicant:</strong>
  <%= @application.applicant %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @application.datetime %>
</p>

<p>
  <strong>Property:</strong>
  <%= @application.property %>
</p>

<p>
  <strong>Status:</strong>
  <%= @application.status %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>