config/routes.rb
Rails.application.routes.draw do
  resources :admins
  root "home#index"
  #get 'home/index', to: "home#index"
  resources :applications
  resources :properties
  resources :applicants
  resources :agents
  resources :admins
  resources :session, only: [:new, :create, :destroy]
  get 'signup', to: "agents#new", as: 'signup'
  get 'app_signup', to: "applicants#new", as: 'app_signup'
  get 'login', to: "session#new", as: 'login'
  get 'logout', to: "session#destroy", as: 'logout'
  get 'admin_signup', to: "admins#new", as: 'admin_signup'
  get 'curr_applications', to: "applications#curr_applications", as: 'curr_applications'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :agent
  validates :property_id, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :size, presence: true
  validates :earliest_start_date, presence: true
  validates :apply_fee, presence: true
  validates :rent, presence: true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.agent_id = current_agent.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:property_id, :name, :address, :size, :terms_available, :earliest_start_date, :apply_fee, :rent, :occupied_by)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.number_field :property_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :terms_available %>
  </div>

  <div class="field">
    <%= form.label :earliest_start_date %>
    <%= form.date_select :earliest_start_date %>
  </div>

  <div class="field">
    <%= form.label :apply_fee %>
    <%= form.number_field :apply_fee %>
  </div>

  <div class="field">
    <%= form.label :rent %>
    <%= form.number_field :rent %>
  </div>

  <div class="field">
    <%= form.label :occupied_by %>
    <%= form.number_field :occupied_by %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>Name</th>
      <th>Address</th>
      <th>Size</th>
      <th>Available</th>
      <th>Earliest start date</th>
      <th>Apply fee</th>
      <th>Rent</th>
      <th>Occupied by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.property_id %></td>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.size %></td>
        <td><%= property.terms_available %></td>
        <td><%= property.earliest_start_date %></td>
        <td><%= property.apply_fee %></td>
        <td><%= property.rent %></td>
        <td><%= property.occupied_by %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @property.id %>
</p>


<p>
  <strong>Property:</strong>
  <%= @property.property_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Size:</strong>
  <%= @property.size %>
</p>

<p>
  <strong>Available:</strong>
  <%= @property.terms_available %>
</p>

<p>
  <strong>Earliest start date:</strong>
  <%= @property.earliest_start_date %>
</p>

<p>
  <strong>Apply fee:</strong>
  <%= @property.apply_fee %>
</p>

<p>
  <strong>Rent:</strong>
  <%= @property.rent %>
</p>

<p>
  <strong>Occupied by:</strong>
  <%= @property.occupied_by %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>